### PR TITLE
fix: nil pointer dereferences in private cluster creation and reconciliation

### LINKED ISSUE #1497: gcpmanagedcontrolplane panics on nil pointer dereference for PrivateClusters
/kind bug

**What steps did you take and what happened:**

Create a GKE Cluster with Private Cluster enabled:

```yaml
kind: GCPManagedControlPlane
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: "capi-cluster1-control-plane"
  namespace: "capi-clusters"
spec:
  clusterName: "capi-cluster1"
  clusterNetwork:
    privateCluster:
      enablePrivateNodes: true
      enablePrivateEndpoint: true
      controlPlaneCidrBlock: "1.2.3.4/28"
  project: "test-project"
  location: "europe-west4"
  endpoint:
    host: "1.2.3.4"
    port: 443
```

CAPG throws nil pointer panics on creation

```
I0723 16:26:35.409885       1 gcpmanagedcontrolplane_controller.go:157] "Reconciling GCPManagedControlPlane" controller="gcpmanagedcontrolplane" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="GCPManagedControlPlane" GCPManagedControlPlane="capi-clusters/capi-cluster1-control-plane" namespace="capi-clusters" name="capi-cluster1-control-plane" reconcileID="b6fecaff-9e43-48b7-8859-52d5d8899d07" controller="gcpmanagedcontrolplane"
I0723 16:26:35.410484       1 reconcile.go:45] "Reconciling cluster resources" controller="gcpmanagedcontrolplane" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="GCPManagedControlPlane" GCPManagedControlPlane="capi-clusters/capi-cluster1-control-plane" namespace="capi-clusters" name="capi-cluster1-control-plane" reconcileID="b6fecaff-9e43-48b7-8859-52d5d8899d07" service="container.clusters"
I0723 16:26:35.455884       1 reconcile.go:55] "Cluster not found, creating" controller="gcpmanagedcontrolplane" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="GCPManagedControlPlane" GCPManagedControlPlane="capi-clusters/capi-cluster1-control-plane" namespace="capi-clusters" name="capi-cluster1-control-plane" reconcileID="b6fecaff-9e43-48b7-8859-52d5d8899d07" service="container.clusters"
E0723 16:26:35.459280       1 signal_unix.go:917] "Observed a panic" controller="gcpmanagedcontrolplane" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="GCPManagedControlPlane" GCPManagedControlPlane="capi-clusters/capi-cluster1-control-plane" namespace="capi-clusters" name="capi-cluster1-control-plane" reconcileID="b6fecaff-9e43-48b7-8859-52d5d8899d07" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
        goroutine 404 [running]:
        k8s.io/apimachinery/pkg/util/runtime.logPanic({0x433cc70, 0xc0011cb410}, {0x3578ee0, 0x63c6420})
                k8s.io/apimachinery@v0.32.3/pkg/util/runtime/runtime.go:107 +0xbc
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()
                sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:108 +0x112
        panic({0x3578ee0?, 0x63c6420?})
                runtime/panic.go:791 +0x132
        sigs.k8s.io/cluster-api-provider-gcp/cloud/services/container/clusters.(*Service).createCluster(0xc00073afb0, {0x433cd18, 0xc000491340}, 0xc000da52a0)
                sigs.k8s.io/cluster-api-provider-gcp/cloud/services/container/clusters/reconcile.go:297 +0x832
        sigs.k8s.io/cluster-api-provider-gcp/cloud/services/container/clusters.(*Service).Reconcile(0xc00073afb0, {0x433cd18, 0xc000491340})
                sigs.k8s.io/cluster-api-provider-gcp/cloud/services/container/clusters/reconcile.go:84 +0x13b0
        sigs.k8s.io/cluster-api-provider-gcp/exp/controllers.(*GCPManagedControlPlaneReconciler).reconcile(0xc001240e10?, {0x433cd18, 0xc000491340}, 0xc0017b9d80)
                sigs.k8s.io/cluster-api-provider-gcp/exp/controllers/gcpmanagedcontrolplane_controller.go:174 +0x462
        sigs.k8s.io/cluster-api-provider-gcp/exp/controllers.(*GCPManagedControlPlaneReconciler).Reconcile(0xc000af52f0, {0x433cc70?, 0xc0011cb410?}, {{{0xc000ecc150?, 0x857b79?}, {0xc000a3f740?, 0x0?}}})
                sigs.k8s.io/cluster-api-provider-gcp/exp/controllers/gcpmanagedcontrolplane_controller.go:152 +0x6c9
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc000e33f40?, {0x433cc70?, 0xc0011cb410?}, {{{0xc000ecc150?, 0x0?}, {0xc000a3f740?, 0x0?}}})
                sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:119 +0xbf
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x4364ee0, {0x433cca8, 0xc000788a50}, {{{0xc000ecc150, 0xd}, {0xc000a3f740, 0x1b}}}, 0x0)
                sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:334 +0x3ad
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x4364ee0, {0x433cca8, 0xc000788a50})
                sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294 +0x21e
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()
                sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255 +0x85
        created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 210
                sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:251 +0x6b8
>
E0723 16:26:35.459466       1 controller.go:347] "Reconciler error" err="panic: runtime error: invalid memory address or nil pointer dereference [recovered]" controller="gcpmanagedcontrolplane" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="GCPManagedControlPlane" GCPManagedControlPlane="capi-clusters/capi-cluster1-control-plane" namespace="capi-clusters" name="capi-cluster1-control-plane" reconcileID="b6fecaff-9e43-48b7-8859-52d5d8899d07"
```

**What did you expect to happen:**
Not have nil pointers thrown 
Have cluster created with private cluster options correctly enabled

**Anything else you would like to add:**

In [reconcile.go:297](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/v1.10.0/cloud/services/container/clusters/reconcile.go#L297) as referenced in the stacktrace, we find the setting of `NetworkConfig.DefaultEnablePrivateNodes`.

This was changed in 1.9.0:
[this commit](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/commit/548fa54a835f518c8ae22431455a6bb66e661184#diff-e0cdc34b85635e4a77bf2660760c32edf85ba31dac9004f213f63e702ad08a0eR293)

from 
```golang
cluster.PrivateClusterConfig.EnablePrivateNodes = cn.PrivateCluster.EnablePrivateNodes
```
to
```golang
cluster.NetworkConfig.DefaultEnablePrivateNodes = &cn.PrivateCluster.EnablePrivateNodes
```

However, `cluster.NetworkConfig` does NOT seem to be set by [cluster var definition](
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/v1.8.1/cloud/services/container/clusters/reconcile.go#L254)

but only by 
[a later step added for SNAT et al](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/cloud/services/container/clusters/reconcile.go#L302)

So `cluster.NetworkConfig` is `nil` we think.

**Environment:**

- Cluster-api version: 1.10.0
- Turtles version: 0.13.0
- Kubernetes version: 1.32
- OS: RHEL9

### PR DESCRIPTION
**Pull request by pkieszcz**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Fixes two nil pointer dereference issues when creating/reconciling private GKE clusters with PSC (Private Service Connect) mode - i.e., when `enablePrivateEndpoint: true` without specifying `controlPlaneCidrBlock`.

### Fix 1: Creation path (related to #1503)

In `createCluster`, `cluster.NetworkConfig.DefaultEnablePrivateNodes` was accessed before `NetworkConfig` was initialized.

**Changes:**
- Initialize `NetworkConfig` before accessing `DefaultEnablePrivateNodes`
- Set `EnablePrivateNodes` on `PrivateClusterConfig` to match (GCP SDK requires both fields to have the same value)

### Fix 2: Reconciliation path

In `checkDiffAndPrepareUpdate`, `clusterUpdate.DesiredControlPlaneEndpointsConfig.IpEndpointsConfig.AuthorizedNetworksConfig` was assigned without initializing the parent structs.

**Changes:**
- Initialize `DesiredControlPlaneEndpointsConfig` and `IpEndpointsConfig` before assigning `AuthorizedNetworksConfig`

**Which issue(s) this PR fixes**:
Fixes #1497

**Special notes for your reviewer**:

This PR combines the fix from #1503 (which was closed) with an additional fix for the reconciliation path. Both issues have the same root cause and affect private cluster functionality.

**Reproduction steps:**
1. Create a GKE cluster with `enablePrivateEndpoint: true` and no `controlPlaneCidrBlock` (PSC mode)
2. Fix 1: Controller panics during cluster creation
3. Fix 2: If cluster is created successfully, controller panics during reconciliation when `master_authorized_networks_config` differs

**TODOs**:
- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
Fix nil pointer dereferences when creating/reconciling private GKE clusters with PSC mode
```

### CODE REVIEW

**Review by salasberryfin — COMMENTED** [review]
/ok-to-test

File: cloud/services/container/clusters/reconcile.go [hunk 1]
```diff
@@ -516,6 +518,12 @@ func (s *Service) checkDiffAndPrepareUpdate(existingCluster *containerpb.Cluster
 	desiredMasterAuthorizedNetworksConfig := convertToSdkMasterAuthorizedNetworksConfig(s.scope.GCPManagedControlPlane.Spec.MasterAuthorizedNetworksConfig)
 	if !compareMasterAuthorizedNetworksConfig(desiredMasterAuthorizedNetworksConfig, existingCluster.GetControlPlaneEndpointsConfig().GetIpEndpointsConfig().GetAuthorizedNetworksConfig()) {
```
Comment (salasberryfin) [inline cloud/services/container/clusters/reconcile.go]: It's probably worth changing this too: 
```go
existingCluster.GetControlPlaneEndpointsConfig().GetIpEndpointsConfig().GetAuthorizedNetworksConfig()
```
`compareMasterAuthorizedNetworksConfig()` deals with nil values and it's safe to use but what if any of the intermediate methods on `existingCluster` returns nil?

Comment (pkieszcz) [reply cloud/services/container/clusters/reconcile.go]: Addressed — extracted the chain into a local `existingAuthorizedNetworksConfig` variable, which also cleans up the repeated chains in the log lines below.

For context: the protobuf generated `Get*()` methods are nil-safe (they check `if x != nil` and return nil), so the chain on `existingCluster` wouldn't panic. But the variable is cleaner regardless.

The actual nil pointer was on the `clusterUpdate` side — `clusterUpdate.DesiredControlPlaneEndpointsConfig.IpEndpointsConfig.AuthorizedNetworksConfig` used direct field access (not getters) on uninitialized structs. That's now guarded with nil checks before assignment.

**Comment by pkieszcz** [comment]
@salasberryfin Thanks for the review! Both comments addressed in the latest force-push:

**Tests:** Added `TestCheckDiffAndPrepareUpdate` covering 7 cases including the nil pointer scenarios (nil `ControlPlaneEndpointsConfig`, nil `IpEndpointsConfig`), plus diff detection for release channel, master version, and authorized networks config. Also added unit tests for the helper functions (`compareMasterAuthorizedNetworksConfig`, `convertToSdkMasterAuthorizedNetworksConfig`, `convertToSdkReleaseChannel`, `convertToSdkMasterVersion`, `convertToSdkBinaryAuthorizationEvaluationMode`).

**Inline comment (chained getters):** Replied on the thread — extracted into a variable for clarity, and explained the nil-safety of protobuf getters vs the actual bug on the `clusterUpdate` side.

File: cloud/services/container/clusters/reconcile.go [hunk 2]
```diff
@@ -514,12 +516,19 @@ func (s *Service) checkDiffAndPrepareUpdate(existingCluster *containerpb.Cluster
 	// DesiredMasterAuthorizedNetworksConfig
 	// When desiredMasterAuthorizedNetworksConfig is nil, it means that the user wants to disable the feature.
 	desiredMasterAuthorizedNetworksConfig := convertToSdkMasterAuthorizedNetworksConfig(s.scope.GCPManagedControlPlane.Spec.MasterAuthorizedNetworksConfig)
-	if !compareMasterAuthorizedNetworksConfig(desiredMasterAuthorizedNetworksConfig, existingCluster.GetControlPlaneEndpointsConfig().GetIpEndpointsConfig().GetAuthorizedNetworksConfig()) {
+	existingAuthorizedNetworksConfig := existingCluster.GetControlPlaneEndpointsConfig().GetIpEndpointsConfig().GetAuthorizedNetworksConfig()
```
Comment (salasberryfin) [inline cloud/services/container/clusters/reconcile.go]: I think this can still trigger a nil pointer dereference. For example, `GetControlPLaneEndpointsConfig` will not fail as `existingCluster` is not nil, but `Cluster.ControlPlaneEndpointsConfig` is a pointer and can be nil which would trigger a chain error as `GetIpEndpointsConfig` would be called on a nil value. Does this make sense?

Comment (pkieszcz) [reply cloud/services/container/clusters/reconcile.go]: ﻿﻿You're right - added explicit nil checks for the getter chain

**Review by salasberryfin — APPROVED** [review]
Thanks @pkieszcz.

/lgtm
/approve

/hold it to give the chance to others to review it.

**Review by salasberryfin — APPROVED** [review]
/unhold

Thanks @pkieszcz.
