### PR TITLE
Fix Cluster Creation in User Provided Subnet

### LINKED ISSUE #896: GCPManagedControlPlane does not come up and requires "Subnet"
/kind bug

**What steps did you take and what happened:**

I created a quickstart GKE cluster and modified the `GCPManagedCluster.spec.network` to include explicit subnets and not create default subnets. Ultimately no cluster comes online and the `GCPManagedControlPlane` throws errors about needing a subnet defined for VPCs in custom subnet mode. 

Full Cluster Spec
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vanilla
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPManagedControlPlane
    name: vanilla-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPManagedCluster
    name: vanilla
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedCluster
metadata:
  name: vanilla
  namespace: default
spec:
  network:
    autoCreateSubnetworks: false
    name: vanilla-vpc
    subnets:
    - cidrBlock: 10.20.96.0/20
      name: nodes-primary
      region: us-central1
    - cidrBlock: 10.21.96.0/20
      name: secondary
      region: us-central1
  project: internal-development-123456
  region: us-central1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedControlPlane
metadata:
  name: vanilla-control-plane
  namespace: default
spec:
  location: us-central1
  project: internal-development-123456
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: vanilla-mp-0
  namespace: default
spec:
  clusterName: vanilla
  replicas: 3
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: vanilla
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPManagedMachinePool
        name: vanilla-mp-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedMachinePool
metadata:
  name: vanilla-mp-0
  namespace: default
spec: {}
```

Steps to recreate local setup
```bash
kind create cluster -n local

export EXP_CAPG_GKE=true
export EXP_MACHINE_POOL=true
clusterctl init --infrastructure gcp

GCP_B64ENCODED_CREDENTIALS=$(cat /Users/bubba/dev/capi/service-account.json | base64 | tr -d '\n') \
  GCP_REGION=us-central1 \
  GCP_PROJECT=internal-development-123456 \
  GCP_NETWORK_NAME=vanilla-vpc \
  clusterctl generate cluster vanilla --flavor gke > gke-vanilla.yaml
  
# Edit GCPManagedCluster.spec.network 
vim gke-vanilla.yaml

$ kubectl apply -f gke-vanilla.yaml
cluster.cluster.x-k8s.io/vanilla created
gcpmanagedcluster.infrastructure.cluster.x-k8s.io/vanilla created
gcpmanagedcontrolplane.infrastructure.cluster.x-k8s.io/vanilla-control-plane created
machinepool.cluster.x-k8s.io/vanilla-mp-0 created
gcpmanagedmachinepool.infrastructure.cluster.x-k8s.io/vanilla-mp-0 created

$ kubectl get GCPManagedControlPlane vanilla-control-plane -o yaml
...
status:
  conditions:
  - lastTransitionTime: "2023-04-13T18:51:26Z"
    message: 'rpc error: code = InvalidArgument desc = Network "vanilla-vpc" uses
      manual subnet mode and requires specifying a subnetwork.'
    reason: GKEControlPlaneReconciliationFailed
    severity: Error
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-04-13T18:51:26Z"
    message: 'rpc error: code = InvalidArgument desc = Network "vanilla-vpc" uses
      manual subnet mode and requires specifying a subnetwork.'
    reason: GKEControlPlaneReconciliationFailed
    severity: Error
    status: "False"
    type: GKEControlPlaneCreating
  - lastTransitionTime: "2023-04-13T18:51:26Z"
    message: 'rpc error: code = InvalidArgument desc = Network "vanilla-vpc" uses
      manual subnet mode and requires specifying a subnetwork.'
    reason: GKEControlPlaneReconciliationFailed
    severity: Error
    status: "False"
    type: GKEControlPlaneReady
  ready: false
```

These are the errors found in capg-controller 
> I0413 20:25:56.414928       1 reconcile.go:51]  "msg"="Cluster not found, creating" "GCPManagedControlPlane"={"name":"vanilla-control-plane","namespace":"default"} "controller"="gcpmanagedcontrolplane" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="GCPManagedControlPlane" "name"="vanilla-control-plane" "namespace"="default" "reconcileID"="97315a96-9174-42e1-8d24-1f2847341b02" "service"="container.clusters"
E0413 20:25:56.951325       1 reconcile.go:268]  "msg"="Error creating GKE cluster" "error"="rpc error: code = InvalidArgument desc = Network \"vanilla-vpc\" uses manual subnet mode and requires specifying a subnetwork." "GCPManagedControlPlane"={"name":"vanilla-control-plane","namespace":"default"} "controller"="gcpmanagedcontrolplane" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="GCPManagedControlPlane" "name"="default-vanilla-control-plane" "namespace"="default" "reconcileID"="97315a96-9174-42e1-8d24-1f2847341b02" "service"="container.clusters"
E0413 20:25:56.951419       1 reconcile.go:80]  "msg"="failed creating cluster" "error"="rpc error: code = InvalidArgument desc = Network \"vanilla-vpc\" uses manual subnet mode and requires specifying a subnetwork." "GCPManagedControlPlane"={"name":"vanilla-control-plane","namespace":"default"} "controller"="gcpmanagedcontrolplane" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="GCPManagedControlPlane" "name"="vanilla-control-plane" "namespace"="default" "reconcileID"="97315a96-9174-42e1-8d24-1f2847341b02" "service"="container.clusters"
E0413 20:25:56.951489       1 gcpmanagedcontrolplane_controller.go:176]  "msg"="Reconcile error" "error"="rpc error: code = InvalidArgument desc = Network \"vanilla-vpc\" uses manual subnet mode and requires specifying a subnetwork." "GCPManagedControlPlane"={"name":"vanilla-control-plane","namespace":"default"} "controller"="gcpmanagedcontrolplane" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="GCPManagedControlPlane" "name"="vanilla-control-plane" "namespace"="default" "reconcileID"="97315a96-9174-42e1-8d24-1f2847341b02" "reconciler"="container_clusters"
E0413 20:25:56.952598       1 controller.go:326]  "msg"="Reconciler error" "error"="rpc error: code = InvalidArgument desc = Network \"vanilla-vpc\" uses manual subnet mode and requires specifying a subnetwork." "GCPManagedControlPlane"={"name":"vanilla-control-plane","namespace":"default"} "controller"="gcpmanagedcontrolplane" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="GCPManagedControlPlane" "name"="vanilla-control-plane" "namespace"="default" "reconcileID"="97315a96-9174-42e1-8d24-1f2847341b02"

**What did you expect to happen:**

This part is kind of fuzzy, because this feature is new and I didn't really know what to expect. Ultimately I think the issue is that I can define subnets that will get created in my VPC, but not set a subnet as the Primary for my nodes. Therefore the GCPManagedControlPlane does not come online with a healthy status.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v1.4.1
- CAPG version: v1.3.0
- Minikube/KIND version: kind v0.16.0 go1.19.1 darwin/arm64
- Kubernetes version: (use kubectl version): Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", - Platform:"darwin/arm64"}
- OS (e.g. from /etc/os-release): MacOS 13.2.1 (22D68) - Darwin Kernel Version 22.3.0

### PR DESCRIPTION
**Pull request by AbdullahAlShaad**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR enables the creation of clusters in user-provided subnets.  It also adds validation for user-provided subnets to ensure that at least one subnet is in the same region where the cluster will be created. The user-provided subnets are created in the intended region rather than the default region.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #896

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:
```release-note
Fix bug for the creation of clusters in user-provided subnets
```

### CODE REVIEW

**Comment by richardcase** [comment]
@Shaad7 - how would you feel about adding an e2e test to cover this scenario?

**Comment by Shaad7** [comment]
@richardcase I have looked the e2e test codes. The cluster template is generated using `clusterctl` commands. There is not flag or export using which I can add a custom subnet. Any idea how can I add e2e test for this ?

**Comment by richardcase** [comment]
> @richardcase I have looked the e2e test codes. The cluster template is generated using `clusterctl` commands. There is not flag or export using which I can add a custom subnet. Any idea how can I add e2e test for this ?

It can be quite time-consuming adding e2e tests, but there is lots of value as it prevents regressions.

If i was doing the work i would probably do this:
- create a new template specifically for use in the e2e tests [here](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/tree/5e7fc149ad3c9996499eba8c91e9dc2aeee4b6ef/test/e2e/data/infrastructure-gcp)
  - Add a envsubst variable for the subnet so that you can replace the token later  
- Add the new template after this entry so clusterctl picks it up: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/5e7fc149ad3c9996499eba8c91e9dc2aeee4b6ef/test/e2e/config/gcp-ci.yaml#L73
- Then in the [e2e_test.go](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/5e7fc149ad3c9996499eba8c91e9dc2aeee4b6ef/test/e2e/e2e_test.go) test file i would create a new **It** under `Context("Creating a single control-plane cluster", func()`  and use the new template created earlier, so something like this:

```go
It("Should create a cluster with 1 worker node with user provided subnets", func() {
                        By("Creating subnets")

                        // Add code to create or get existing subnets in GCP

			By("Initializes with 1 worker node")
			clusterctl.ApplyClusterTemplateAndWait(ctx, clusterctl.ApplyClusterTemplateAndWaitInput{
				ClusterProxy: bootstrapClusterProxy,
				ConfigCluster: clusterctl.ConfigClusterInput{
					LogFolder:                clusterctlLogFolder,
					ClusterctlConfigPath:     clusterctlConfigPath,
					KubeconfigPath:           bootstrapClusterProxy.GetKubeconfigPath(),
					InfrastructureProvider:   clusterctl.DefaultInfrastructureProvider,
					Flavor:                   "newtemplateflavour", // <- this is where we specify the new template
					Namespace:                namespace.Name,
					ClusterName:              clusterName,
					KubernetesVersion:        e2eConfig.GetVariable(KubernetesVersion),
					ControlPlaneMachineCount: pointer.Int64Ptr(1),
					WorkerMachineCount:       pointer.Int64Ptr(1),
                                        ClusterctlVariables: map[string]string{
						"SUBNET": subnetid,
					},
				},
				WaitForClusterIntervals:      e2eConfig.GetIntervals(specName, "wait-cluster"),
				WaitForControlPlaneIntervals: e2eConfig.GetIntervals(specName, "wait-control-plane"),
				WaitForMachineDeployments:    e2eConfig.GetIntervals(specName, "wait-worker-nodes"),
			}, result)
              })
     })
```

**Comment by Shaad7** [comment]
Thank you @richardcase . I have added e2e test for the scenario. Can you have a look ?

File: test/e2e/e2e_test.go [hunk 1]
```diff
@@ -182,4 +182,33 @@ var _ = Describe("Workload cluster creation", func() {
...
+		It("Should create a cluster with 1 worker node and can be scaled", func() {
+			By("Initializes with 1 worker node")
+			clusterctl.ApplyClusterTemplateAndWait(ctx, clusterctl.ApplyClusterTemplateAndWaitInput{
+				ClusterProxy: bootstrapClusterProxy,
+				ConfigCluster: clusterctl.ConfigClusterInput{
+					LogFolder:                clusterctlLogFolder,
+					ClusterctlConfigPath:     clusterctlConfigPath,
+					KubeconfigPath:           bootstrapClusterProxy.GetKubeconfigPath(),
+					InfrastructureProvider:   clusterctl.DefaultInfrastructureProvider,
+					Flavor:                   clusterctl.DefaultFlavor,
```
Comment (richardcase) [inline test/e2e/e2e_test.go:196]: The flavour will need to be set to `ci-gke-custom-subnet` so that it picks up your template file.

File: test/e2e/e2e_test.go [hunk 2]
```diff
@@ -182,4 +182,33 @@ var _ = Describe("Workload cluster creation", func() {
...
+					Namespace:                namespace.Name,
+					ClusterName:              clusterName,
+					KubernetesVersion:        e2eConfig.GetVariable(KubernetesVersion),
+					ControlPlaneMachineCount: pointer.Int64Ptr(1),
+					WorkerMachineCount:       pointer.Int64Ptr(1),
+					ClusterctlVariables: map[string]string{
+						"GCP_SUBNET_NAME": "capg-test-subnet",
```
Comment (richardcase) [inline test/e2e/e2e_test.go:203]: Do we need to create this subnet (`capg-test-subnet`) before running the test? Guessing so......

**Review by richardcase — COMMENTED** [review]
@Shaad7 - thanks for adding the e2e test. A coupld of comments on it. Currently the test isn't using the new template you added.

File: test/e2e/e2e_test.go (hunk 1 above)
Comment (Shaad7) [reply test/e2e/e2e_test.go]: Updated

File: test/e2e/e2e_test.go (hunk 2 above)
Comment (Shaad7) [reply test/e2e/e2e_test.go:203]: No, we don't need to create the subnet. We just need to specify the name and CIDR range. capg operator will create the subnet.

**Comment by richardcase** [comment]
Thanks @AbdullahAlShaad . From my side:

/approve

**Comment by richardcase** [comment]
For final eyes and lgtm

/assign cpanato

**Review by cpanato — APPROVED** [review]
thanks

/lgtm
/approve
