### PR TITLE
Use SetLabels() to set ForwardingRules labels

### LINKED ISSUE #1276: ForwardingRules' labels must be added via the SetLabels() method
/kind bug

**What steps did you take and what happened:**
In https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1275, the ForwardingRules `Labels`  field was set in the resource definition. It turns out that some resources, including ForwardingRules, require the` SetLabels() ` method to add the labels. This is the comment for ForwardingRules in https://github.com/googleapis/google-api-go-client/blame/main/compute/v1/compute-gen.go
```
       // Labels: Labels for this resource. These can only be added or modified
        // by the setLabels method. 
        Labels map[string]string `json:"labels,omitempty"
```

This is different than other resources, for example Instances and Disks, in which the Label can be set in the resource and later modified using `SetLabels()`. This is the description in compute-gen.go
```
        // Labels: Labels to apply to this instance. These can be later modified
        // by the setLabels method.
        Labels map[string]string `json:"labels,omitempty"`
```

**What did you expect to happen:**
So, the end result is that the change to add Labels to the resources when creating it works fine for Disks but does not work for ForwardingRules which require `SetLabels() `to be used after the resource is create.

**Anything else you would like to add:**
Will need to change ForwardingRules to use `SetLabels() `.

**Environment:**
Openshift 4.16 using cluster-api-provider-gcp as provider.

### PR DESCRIPTION
**Pull request by bfournie**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

The ForwardingRules resource requires that the SetLabels() method be used to add the labels after the resource has been created. This resource is different than, for example, Instances or Disks. See Issue #1276 for more information.

**Which issue(s) this PR fixes** 
Fixes #1276 

**Special notes for your reviewer**:

This is the comment for `ForwardingRules` in https://github.com/googleapis/google-api-go-client/blame/main/compute/v1/compute-gen.go
```
       // Labels: Labels for this resource. These can only be added or modified
       // by the setLabels method. 
        Labels map[string]string `json:"labels,omitempty"
```

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
"NONE"
```

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
/ok-to-test

File: cloud/services/compute/loadbalancers/reconcile.go [hunk 1]
```diff
@@ -579,6 +580,19 @@ func (s *Service) createOrGetForwardingRule(ctx context.Context, lbname string,
...
+	labels := s.scope.AdditionalLabels()
+	if !reflect.DeepEqual(labels, forwarding.Labels) {
+		setLabelsRequest := &compute.GlobalSetLabelsRequest{
+			LabelFingerprint: forwarding.LabelFingerprint,
+			Labels:           labels,
+		}
+		err = s.forwardingrules.SetLabels(ctx, key, setLabelsRequest)
+		if err != nil {
+			return nil, err
+		}
```
Comment (damdo) [inline cloud/services/compute/loadbalancers/reconcile.go:593]: How about
```suggestion
		if err := s.forwardingrules.SetLabels(ctx, key, setLabelsRequest); err != nil {
			return nil, err
		}
```

File: cloud/services/compute/loadbalancers/reconcile.go [hunk 2]
```diff
@@ -579,6 +580,19 @@ func (s *Service) createOrGetForwardingRule(ctx context.Context, lbname string,
 		}
 	}
 
+	// Labels on ForwardingRules must be added after resource is created
+	labels := s.scope.AdditionalLabels()
+	if !reflect.DeepEqual(labels, forwarding.Labels) {
```
Comment (damdo) [inline cloud/services/compute/loadbalancers/reconcile.go:585]: Just to confirm, this is a map right? So ordering should not be an issue while diffing correct?

File: cloud/services/compute/loadbalancers/reconcile.go [hunk 3]
```diff
@@ -622,6 +636,19 @@ func (s *Service) createOrGetRegionalForwardingRule(ctx context.Context, lbname
...
+		setLabelsRequest := &compute.RegionSetLabelsRequest{
+			LabelFingerprint: forwarding.LabelFingerprint,
+			Labels:           labels,
+		}
+		err = s.regionalforwardingrules.SetLabels(ctx, key, setLabelsRequest)
+		if err != nil {
+			return nil, err
+		}
```
Comment (damdo) [inline cloud/services/compute/loadbalancers/reconcile.go:649]: Same here :)

File: cloud/services/compute/loadbalancers/reconcile.go (hunk 2 above)
Comment (bfournie) [reply cloud/services/compute/loadbalancers/reconcile.go]: Yes it is a map. There's actually a predefined function https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/api/v1beta1/labels.go#L29-L31 that I changed to use.

File: cloud/services/compute/loadbalancers/reconcile.go (hunk 3 above)
Comment (bfournie) [reply cloud/services/compute/loadbalancers/reconcile.go]: Fixed.

File: cloud/services/compute/loadbalancers/reconcile.go (hunk 1 above)
Comment (bfournie) [reply cloud/services/compute/loadbalancers/reconcile.go]: Thanks, fixed.

**Review by damdo — COMMENTED** [review]
/lgtm

/assign @cpanato
